import Options
from os import unlink, symlink, popen
from os.path import exists

srcdir = "."
blddir = "build"
VERSION = "0.0.1"

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon")
  obj.uselib = ['LIBMOSQUITTO']
  obj.target = "mosquitto"
  obj.source = "mosquitto.cc"

def shutdown():
  if Options.commands['clean']:
    if exists('mosquitto.node'): unlink('mosquitto.node')
  else:
    if exists('build/default/mosquitto.node') and not exists('mosquitto.node'):
      symlink('build/default/mosquitto.node', 'mosquitto.node')