#!/bin/sh

# Peter Siering <ps@ctmagazin.de>, 10/2/2003

ACTION=$1

# Upgrade <= 1.2.6-26 to a more FHS-conform directory structure
#

if [ "$ACTION" = "configure" ] ; then
	# ensure that user and group 'vdr' exist
	USER=www-data
	GROUP=www-data
	if ! getent group | grep -q "^$GROUP:" ; then
		exit 0
	fi
	if ! getent passwd | grep -q "^$USER:"; then
		exit 0
	fi

	if [ -e /usr/share/vdr-guia ] ; then
		chown -R $USER:$GROUP /usr/share/vdr-guia
		chown $USER:$GROUP /usr/share/vdr-guia/* > /dev/null 2>&1 || true
        	chown -r $USER:$GROUP /var/log/guia
	fi
fi

#DEBHELPER#

exit 0